name: Publish WordPress Plugin via SVN

on:
  push:
    branches:
      - main
    # El workflow se ejecuta solo cuando se hace un push a la rama main.

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Paso 2: Obtener versión desde readme.txt
      - name: Get version from readme.txt
        id: version
        run: |
          # Buscar el valor de 'Stable tag' en el archivo readme.txt
          if grep -q "^Stable tag:" readme.txt; then
            VERSION=$(grep "^Stable tag:" readme.txt | awk -F': ' '{print $2}')
          else
            echo "❌ Stable tag not found at readme.txt"
            exit 1
          fi
          echo "🚀 VERSION TO BE RELEASED ➡️  ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Paso 3: Publicar el plugin en SVN
      - name: Publish to SVN
        run: |
          # Instala SVN
          sudo apt-get install -y subversion

          # Configura los credenciales SVN (configurados en el repositorio cómo admin)
          SVN_USER=${{ secrets.SVN_USER }}
          SVN_PASS=${{ secrets.SVN_PASS }}
          SVN_URL="https://plugins.svn.wordpress.org/local-structured-schema-data-for-articles"
          TAGS_DIR="$SVN_URL/tags/${VERSION}"

          # Creamos un directorio temporal
          mkdir -p /tmp/plugin
          echo "✅ /tmp/plugin directory created."

          # Clonamos el repositorio SVN
          svn checkout $SVN_URL /tmp/plugin

          # Nos aseguramos de que la carpeta Tags tenga un subdirectorio para la nueva versión
          echo "📂 Creating new version directory: ${TAGS_DIR}"
          mkdir -p /tmp/plugin/tags/${VERSION}

          # Copia los archivos especificados a la carpeta de la nueva versión
          cp readme.txt schema-structured-data-article.php /tmp/plugin/tags/${VERSION}/

          # Lista los archivos en la carpeta de la nueva versión
          echo "🗂️  Files in /tmp/plugin/tags/${VERSION}:"
          ls -la /tmp/plugin/tags/${VERSION}

          # Preparamos los cambios para subirlos a SVN
          cd /tmp/plugin
          svn add * --force
          svn commit -m "Nueva versión ${VERSION}" --username $SVN_USER --password $SVN_PASS

          # Limpia la carpeta temporal
          cd /
          rm -rf /tmp/plugin
          echo "🧹 /tmp/plugin directory removed."
