name: Publish WordPress Plugin via SVN

on:
  push:
    branches:
      - main
    # El workflow se ejecuta solo cuando se hace un push a la rama main.

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Paso 2: Publicar el plugin en SVN
      - name: Publish to SVN
        run: |
          # Instala SVN
          sudo apt-get install -y subversion


          # Creamos un directorio temporal
          mkdir -p /tmp/plugin
          echo "✅ /tmp/plugin directory created."

          # Nos aseguramos de que la carpeta Tags tenga un subdirectorio para la nueva versión
          echo "📂 Creating new version directory: ${TAGS_DIR}"
          mkdir -p /tmp/plugin/tags/${VERSION}

          # Copia los archivos especificados a la carpeta de la nueva versión
          cp readme.txt schema-structured-data-article.php /tmp/plugin/tags/${VERSION}/

          # Lista los archivos en la carpeta de la nueva versión
          echo "🗂️  Files in /tmp/plugin/tags/${VERSION}:"
          ls -la /tmp/plugin/tags/${VERSION}

          # Preparamos los cambios para subirlos a SVN
          cd /tmp/plugin
